---
- name: create web directory
  file:
    path: ~/backend_content
    state: directory

# - name: extract zipped backend content from local
#   unarchive:
#     src: ~/artifact.tar.gz
#     dest: ~/backend_content

# - name: create web directory2
#   file:
#     path: ~/backend_content2
#     state: directory

- name: extract zipped backend content
  shell: |
    tar xvzf /tmp/artifact.tar.gz --directory ~/backend_content
  register: test_output

- debug:
    var: test_output

- name: start udapeople backend app
  shell: |
    cd ~/backend_content
    npm install
    pm2 stop default
    pm2 start npm -- start
