---
- name: create web directory
  file:
    path: ~/backend_content
    state: directory

- name: extract zipped backend content
  shell: |
    tar xvzf /tmp/artifact.tar.gz --directory ~/backend_content
    # backend/artifact.tar.gz
  register: test_output

- debug:
    var: test_output

# - name: start web server
#   command: pm2 start ~/web/index.js -f
