---
- name: create web directory
  file:
    path: ~/backend_content
    state: directory

- name: extract zipped backend content from local
  unarchive:
    src: ~/artifact.tar.gz
    dest: ~/backend_content

- name: list backend_content dir on host
  shell: |
    ls ~/backend_content
  register: test_output1

- debug:
    var: test_output1

- name: extract zipped backend content
  shell: |
    ls /
    ls /tmp
    #tar xvzf /tmp/artifact.tar.gz --directory ~/backend_content
    # backend/artifact.tar.gz
  register: test_output

- debug:
    var: test_output

# - name: start web server
#   command: pm2 start ~/web/index.js -f
