---
- name: create web directory
  file:
    path: ~/backend_content
    state: directory

- name: extract zipped backend content
  shell: |
    ls /root/project
    ls ~/
    # backend/artifact.tar.gz

# - name: start web server
#   command: pm2 start ~/web/index.js -f
