---
- name: "update apt packages."
#  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
#  become: yes
  apt:
    upgrade: yes

- name: install prerequisites
  apt:
    name:
      - python3
      - nodejs
      - npm
    state: latest

- name: install pm2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


