version: 2.1

orbs:
  slack: circleci/slack@4.1

commands:
  notify-on-fail:
    parameters:
      channel:
        type: string
        default: "general"
    steps:
      - slack/notify:
          channel: << parameters.channel >>
          event: fail
          template: basic_fail_1

# Job definitions
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - notify-on-fail:
          channel: build-failures
  
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - notify-on-fail:
          channel: build-failures

  test-frontend:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # Restore from cache
      - run:
          name: run FrontEnd tests
          command: |
            cd frontend
            npm install
            npm run test
      - notify-on-fail:
          channel: code-test-failures

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # Restore from cache
      - run:
          name: run BackEnd tests
          command: |
            cd backend
            npm install
            npm run test
      - notify-on-fail:
          channel: code-test-failures

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # Restore from cache
      - run:
          name: Audit Frontend code
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # Restore from cache
      - run:
          name: Audit backend code
          command: |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force

  

# Workflow definitions
workflows:
  build_and_test:
    jobs:
      - build-frontend:
          context:
            - slack-vars
      - build-backend:
          context:
            - slack-vars
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - scan-backend:
          requires: [build-backend]
